# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registers_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(655, 577)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setMinimumSize(QtCore.QSize(580, 510))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 9, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "ANC_L2"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "ANC_R2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "ANC_L3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "ANC_R3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "ANC_MODE"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "MON_MODE"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "PBO_MODE"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "ECO"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "SYSTEM"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "POR_SET"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "MIC_MON_L"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "MIC_MON_R"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "ANC_R"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "ANC_L"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "MODE_1"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "MODE_2"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "EVAL"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "CONFIG_1"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("Dialog", "CONFIG_2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Addr"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "Value"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(0, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(0, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(0, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(1, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(1, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(1, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(2, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(2, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(2, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(3, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(3, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(3, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(4, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(4, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(4, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(4, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(5, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(5, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(5, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(5, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(5, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(6, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(6, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(6, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(6, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(6, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(7, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(7, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(7, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(7, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(7, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(8, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(8, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(8, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(8, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(8, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(8, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(9, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(9, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(9, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(9, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(9, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(9, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(9, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(10, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(10, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(10, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(10, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(10, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(10, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(10, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(11, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(11, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(11, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(11, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(11, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(11, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(11, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(12, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(12, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(12, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(12, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(12, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(12, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(12, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(13, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(13, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(13, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(13, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(13, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(13, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(13, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(13, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(14, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(14, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(14, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(14, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(14, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(14, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(14, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(14, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(14, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(15, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(15, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(15, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(15, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(15, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(15, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(15, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(15, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(15, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(16, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(16, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(16, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(16, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(16, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(16, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(16, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(16, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(16, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(17, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(17, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(17, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(17, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(17, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(17, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(17, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(17, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(17, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(17, 9)
        item.setText(_translate("Dialog", "0x00"))
        item = self.tableWidget.item(18, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(18, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(18, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(18, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(18, 4)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(18, 5)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(18, 6)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(18, 7)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(18, 8)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(18, 9)
        item.setText(_translate("Dialog", "0x00"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

