#!/usr/bin/env python 
# -*- coding:utf-8 -*-
# @Time    : 2019-1-26 21:02
# @Author  : liujin_person
import re


def re_rc_bom(circuit_str):
    """
    根据电路网表图，利用正则表达式输出电路BOM表（仅电阻电容）
    :param circuit_str: str格式电路网表图,example：C1 0 NetC1_2 220n
    :return: d={'C1':'220n'}
    """

    if isinstance(circuit_str, str):

        List = circuit_str.split('\n')

        re_RC_BOM = re.compile(r'^([RC]\w+)\s+([\w_]+)\s+([\w_]+)\s([\w.]+)$')

        d = dict()
        for i in range(len(List)):
            if re_RC_BOM.match(List[i]):
                d[re_RC_BOM.match(List[i]).group(1)] = re_RC_BOM.match(List[i]).group(4)

        return d

    else:
        raise TypeError('输入必须是str格式的电路网表')


if __name__ == "__main__":
    circuit = r'''FF_ANC
    *SPICE Netlist generated by Advanced Sim server on 2019-1-12 15:01:53
    
    *Schematic Netlist:
    C1 0 NetC1_2 220n
    C2 NetC2_1 OUTPUT 4.7u
    C3 NetC3_1 NetC3_2 33n
    C4 NetC3_2 NetC4_2 33n
    C8 NetC3_1 OUTPUT 470p
    C9 NetC9_1 NetC9_2 2.2u
    C10 0 NetC10_2 330n
    C14 NetC14_1 NetC3_1 33n
    C15 INPUT NetC15_2 6.8n
    C16 NetC15_2 NetC16_2 6.8n
    R1 NetC3_1 NetC1_2 1k
    R2 NetC1_2 NetC4_2 1k
    R3 NetC4_2 NetC2_1 510
    R5 0 NetC3_2 10k
    R8 NetC9_2 VMIC 2.2k
    R9 INPUT NetC10_2 2.2k
    R10 NetC10_2 NetC16_2 2.2k
    R13 NetC9_2 NetR13_2 0
    R14 NetC9_1 0 22K
    R15 NetC16_2 NetC14_1 2k
    R16 INPUT NetR16_2 47k
    R17 0 NetC15_2 1k
    R19 0 NetR16_2 10k
    Rf1 NetC4_2 OUTPUT 20k
    Ri1 NetC16_2 NetC3_1 10k
    XU1 NetC9_1 NetR16_2 VPOS VNEG INPUT UA741
    XU2 0 NetC3_1 VPOS VNEG OUTPUT UA741
    V1 VPOS 0 5V
    V2 VMIC 0 2.7V
    V3 0 VNEG 5V
    Vin1 NetR13_2 0 DC 0 SIN(0 0.05 10k 0 0) AC 1 180'''
    BOM = re_rc_bom(circuit)  # 不清楚为什么，这个模式下BOM为空
    a = ['%s  %s\n' % (k, v) for k, v in BOM.items()]
    with open('E:\python_company\pyspice_learn\my_spice\FF BOM.txt', 'w') as f:
        f.writelines(a)
